# Generated by Django 5.1.3 on 2024-12-03 19:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelConsumption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fuel_used', models.FloatField(help_text='Amount of fuel used in liters or gallons')),
                ('fuel_efficiency', models.FloatField(help_text='Fuel efficiency (e.g., km/l or mpg)')),
                ('unit', models.CharField(choices=[('liters', 'Liters'), ('gallons', 'Gallons')], default='liters', help_text='Unit of fuel used', max_length=10)),
                ('efficiency_unit', models.CharField(choices=[('km/l', 'Kilometers per Liter'), ('mpg', 'Miles per Gallon')], default='km/l', help_text='Unit of fuel efficiency', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the fuel consumption data was recorded')),
                ('vehicle', models.ForeignKey(help_text='The vehicle associated with this fuel consumption entry', on_delete=django.db.models.deletion.CASCADE, related_name='fuel_consumptions', to='vehicle.vehicle')),
            ],
        ),
    ]
